//
//  CardReaderPresenter.swift
//  IDCardReader
//
//  Created by Sharon Varghese on 28/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardReaderPresentationLogic
{
    func showProgressUpdate(progress: Double)
    func initializationCompletedSuccessfully()
    func initializationFailed(reason: String)
    func displayResults(results: [Any])
}

class CardReaderPresenter: CardReaderPresentationLogic
{
    
    weak var viewController: CardReaderDisplayLogic?
    
    func displayResults(results: [Any]) {
        viewController?.displayResults(results: results)
    }
    func initializationFailed(reason: String) {
        viewController?.initializationFailed(errorMessage: reason)
    }
    
    func initializationCompletedSuccessfully() {
        viewController?.initializationCompletedSuccessfully()
    }

    func showProgressUpdate(progress: Double) {
        viewController?.displayInitializationProgress(progress: Float(progress))
    }
    
 
  
}
